apiVersion: v2
name: hercules-ci-agent
description: Helm chart for installing the Hercules CI agent
type: application
version: 0.2.0
# renovate: image=ghcr.io/unmango/hercules-ci-agent
appVersion: 0.10.8
sources:
  - https://github.com/hercules-ci/hercules-ci-agent
  - https://github.com/unmango/containers/tree/main/images/hercules-ci-agent
kubeVersion: '>= 1.25'
maintainers:
  - name: UnstoppableMango
    url: https://github.com/UnstoppableMango
