{{- if and .Values.auth.password (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.auth.passwordKey }}: {{ .Values.auth.password | quote }}
{{- end }}
