apiVersion: v2
name: deluge
description: Helm chart for installing Deluge behind a gluetun VPN sidecar
type: application
version: 0.1.0
# renovate: image=lscr.io/linuxserver/deluge
appVersion: 2.2.0-ls371
sources:
  - https://github.com/deluge-torrent/deluge
  - https://github.com/linuxserver/docker-deluge
kubeVersion: '>= 1.29'
maintainers:
  - name: UnstoppableMango
    url: https://github.com/UnstoppableMango
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 2.41.0
  - name: gluetun
    version: '>= 0.1.0'
    repository: file://../gluetun
