{{- if include "manageSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.auth.existingSecretKey }}: {{ .Values.auth.password | required "auth.password is required when auth.enabled is set and auth.existingSecret is not" | quote }}
{{- end }}
