{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.auth.adminPasswordKey }}: {{ include "adminPassword" . | quote }}
  {{- with .Values.auth.serverPassword }}
  {{ $.Values.auth.serverPasswordKey }}: {{ . | quote }}
  {{- end }}
{{- end }}
