{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
type: Opaque
stringData:
  mongodb-password: {{ include "password" (dict "ctx" . "key" "mongodb-password" "value" .Values.database.password) | quote }}
  {{- if .Values.mongodb.enabled }}
  mongodb-root-password: {{ include "password" (dict "ctx" . "key" "mongodb-root-password" "value" .Values.mongodb.rootPassword) | quote }}
  {{- end }}
{{- end }}
