apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "LoadBalancer") (.Values.service.loadBalancerIP) }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: controller
  ports:
    - name: https
      port: {{ .Values.service.ports.https }}
      targetPort: https
    - name: inform
      port: {{ .Values.service.ports.inform }}
      targetPort: inform
    - name: stun
      port: {{ .Values.service.ports.stun }}
      targetPort: stun
      protocol: UDP
    - name: discovery
      port: {{ .Values.service.ports.discovery }}
      targetPort: discovery
      protocol: UDP
