# Generates the parts of this chart that come from upstream: templates/_upstream.tpl
# and upstream-values.yaml.
#
# This chart renders N scale sets from one release, so it cannot use upstream's
# templates as files: helm renders a template file once, against one .Values.
# The same tree is instead wrapped so each resource becomes a named template
# this chart can include repeatedly, once per entry, against a synthesized root.
#
# The upstream pin and the patches under ../gha-runner-scale-set are shared with
# the single-scale-set chart, so a bump or a patch edit lands in both. The
# generated tree is committed anyway so that ct, chart-releaser and
# `helm template` all work against the worktree without a Nix step, and CI fails
# when the two disagree. `make chart-gha-runner-scale-sets` is the regeneration
# entry point.
{
  fetchFromGitHub,
  lib,
  runCommand,
}:
let
  upstream = import ../gha-runner-scale-set/upstream.nix;

  src = fetchFromGitHub {
    inherit (upstream) owner repo hash;
    tag = "gha-runner-scale-set-${upstream.version}";
  };

  patches =
    lib.filesystem.listFilesRecursive ../gha-runner-scale-set/patches
    |> lib.filter (lib.hasSuffix ".patch");
in
runCommand "gha-runner-scale-sets-chart-${upstream.version}"
  {
    inherit patches;
    inherit (upstream) chartPath;
    src = "${src}/${upstream.chartPath}";
  }
  ''
    cp -r "$src" chart
    chmod -R u+w chart

    for patch in $patches; do
      echo "applying $(basename "$patch")"
      patch -d chart -p1 --no-backup-if-mismatch < "$patch"
    done

    mkdir -p "$out/templates"

    # _helpers.tpl is already nothing but defines, so it carries over verbatim.
    # Its templates read $.Values, which resolves to whatever the outermost
    # define was handed, i.e. the synthesized root, not this chart's real one.
    {
      echo '{{/*'
      echo '  Generated by charts/gha-runner-scale-sets/package.nix. Do not edit.'
      echo "  Wraps the ''${chartPath##*/} chart at ${upstream.version}"
      echo '  so each resource can be rendered once per entry in .Values.scaleSets.'
      echo '*/}}'
      echo
      cat chart/templates/_helpers.tpl
      echo

      for f in chart/templates/*.yaml; do
        name="$(basename "$f" .yaml)"
        echo "{{- define \"gha-runner-scale-sets.upstream.$name\" -}}"
        cat "$f"
        echo '{{- end -}}'
        echo
      done
    } > "$out/templates/_upstream.tpl"

    # Upstream's defaults, which this chart merges under every entry. The
    # templates dereference values.yaml keys without guarding them, so an entry
    # rendered against defaults alone fails on a nil map.
    {
      echo '# Generated by charts/gha-runner-scale-sets/package.nix. Do not edit.'
      echo '#'
      echo '# The gha-runner-scale-set values.yaml at ${upstream.version}, read at render'
      echo '# time via .Files.Get and merged under each entry in .Values.scaleSets.'
      echo '# Not this chart values.yaml, and not overridable with --set; override'
      echo '# through .Values.defaults instead.'
      echo
      cat chart/values.yaml
    } > "$out/upstream-values.yaml"
  ''
