{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secretName" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{ .Values.existingSecretKey }}: {{ .Values.clusterJoinToken | required "clusterJoinToken is required unless existingSecret is set" | quote }}
  binary-caches.json: {{ .Values.binaryCaches | toJson | quote }}
  secrets.json: {{ .Values.secretsJson | toJson | quote }}
{{- end }}
