{{- if include "renderSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secretName" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- if not .Values.existingSecret }}
  {{ .Values.existingSecretKey }}: {{ .Values.clusterJoinToken | quote }}
  {{- end }}
  {{- with .Values.secretsJson }}
  secrets.json: {{ . | toJson | quote }}
  {{- end }}
{{- end }}
