{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secretName" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{ .Values.existingSecretKey }}: {{ .Values.clusterJoinToken | required "clusterJoinToken is required unless existingSecret is set" | quote }}
  {{- with .Values.secretsJson }}
  secrets.json: {{ . | toJson | quote }}
  {{- end }}
{{- end }}
