clusterJoinToken: dummy-token-for-linting
persistence:
  enabled: false
  emptyDir:
    sizeLimit: 10Gi
resources:
  requests:
    cpu: '2'
    memory: 8Gi
    ephemeral-storage: 10Gi
  limits:
    memory: 16Gi
