{{- if include "manageSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secretName" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  mail-password: {{ .Values.mail.password | quote }}
  mailgun-api-key: {{ .Values.mail.mailgunApiKey | quote }}
{{- end }}
