{{- with .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "labels" $ | nindent 4 }}
data:
  config.toml: |
    {{- . | nindent 4 }}
{{- end }}
