name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint:
    runs-on: unmango-runners
    strategy:
      matrix:
        chart:
          - deemix
          - filebrowser
    steps:
      - uses: actions/checkout@v5

      - run: make lint-${{ matrix.chart }}
