name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chart:
          - deemix
          - filebrowser
    env:
      # renovate: datasource=github-releases depName=helm/chart-testing
      CHART_TESTING_VERSION: 3.13.0
      # renovate: datasource=github-releases depName=helm/helm
      HELM_VERSION: 3.19.0
      # renovate: datasource=pypi depName=yamale
      YAMALE_VERSION: 6.0.0
      # renovate: datasource=pypi depName=yamllint
      YAMLLINT_VERSION: 1.37.1
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # Required by yamale and yamllint
      - uses: actions/setup-python@v6.0.0
        with:
          python-version: '3.x'

      - uses: azure/setup-helm@v4.3.1
        with:
          version: v${{ env.HELM_VERSION }}

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0
        with:
          version: ${{ env.CHART_TESTING_VERSION }}
          yamale_version: ${{ env.YAMALE_VERSION }}
          yamllint_version: ${{ env.YAMLLINT_VERSION }}

      - run: helm dep update charts/${{ matrix.chart }}
      - run: helm lint charts/${{ matrix.chart }}
      - run: ct lint charts/${{ matrix.chart }}
