name: CI

on:
  pull_request:
    branches: [main]

env:
  # renovate: datasource=github-releases depName=helm/chart-testing
  CHART_TESTING_VERSION: 3.14.0
  # renovate: datasource=github-releases depName=helm/helm
  HELM_VERSION: 4.1.4
  # renovate: datasource=github-releases depName=kubernetes-sigs/kind
  KIND_VERSION: 0.31.0
  # renovate: datasource=pypi depName=yamale
  YAMALE_VERSION: 6.1.0
  # renovate: datasource=pypi depName=yamllint
  YAMLLINT_VERSION: 1.38.0

jobs:
  nix:
    runs-on: unmango-runners
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: cachix/install-nix-action@ab739621df7a23f52766f9ccc97f38da6b7af14f # v31
        with:
          extra_nix_config: |
            extra-trusted-public-keys = ncps.thecluster.lan:D8fcKW2/D+zjKOABa3bDjEe8x+EPZpXnBDm+XwtNrhI=
            extra-substituters = https://ncps.thecluster.lan

      - uses: cachix/cachix-action@1eb2ef646ac0255473d23a5907ad7b04ce94065c # v17
        with:
          name: unstoppablemango

      - uses: DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39 # v13

      - run: nix flake check

  lint:
    runs-on: unmango-runners
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      # Required by yamale and yamllint
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.x'

      - uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5
        with:
          version: v${{ env.HELM_VERSION }}

      - name: Set up chart-testing
        uses: helm/chart-testing-action@6ec842c01de15ebb84c8627d2744a0c2f2755c9f # v2.8.0
        with:
          version: ${{ env.CHART_TESTING_VERSION }}
          yamale_version: ${{ env.YAMALE_VERSION }}
          yamllint_version: ${{ env.YAMLLINT_VERSION }}

      - run: |
          for chart in charts/*; do
            helm dep update "$chart"
          done

      - run: ct lint --config .ct.yaml --github-groups

  test:
    runs-on: unmango-runners
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5
        with:
          version: v${{ env.HELM_VERSION }}

      - name: Set up chart-testing
        uses: helm/chart-testing-action@6ec842c01de15ebb84c8627d2744a0c2f2755c9f # v2.8.0
        with:
          version: ${{ env.CHART_TESTING_VERSION }}
          yamale_version: ${{ env.YAMALE_VERSION }}
          yamllint_version: ${{ env.YAMLLINT_VERSION }}

      - uses: helm/kind-action@ef37e7f390d99f746eb8b610417061a60e82a6cc # v1
        with:
          version: v${{ env.KIND_VERSION }}
          config: kind-cluster.yml

      - run: |
          ct install --config .ct.yaml \
          --github-groups \
          --excluded-charts filebrowser
