name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chart:
          - deemix
          - filebrowser
    steps:
      - uses: actions/checkout@v5

      - run: make lint-${{ matrix.chart }}

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

