name: Release

on:
  push:
    branches: [ main ]

env:
  # renovate: datasource=github-releases depName=helm/helm
  HELM_VERSION: 4.1.4

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - uses: azure/setup-helm@v5
        with:
          version: v${{ env.HELM_VERSION }}

      - run: helm repo add oauth2-proxy https://oauth2-proxy.github.io/manifests

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          config: .cr.yaml
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
