name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: thecluster-runners
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - run: helm repo add oauth2-proxy https://oauth2-proxy.github.io/manifests

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          config: .cr.yaml
